export const faq = {
    pl:{
        seo:{
            title:'Pytania i odpowiedzi - poznaj mnie, strony www, SEO - RadWEB',
            desc:'Chcesz się dowiedzieć więcej na mój temat? Chcesz zadać swoje unikalne pytanie? Tutaj jest przestrzeń, gdzie odpowiadam na najpopularniejsze pytania.'
        },
        hero:{
            title:'FAQ - pytania i odpowiedzi',
            content:'Chcesz się dowiedzieć więcej na temat mojej osoby oraz tego co robię? Otrzymasz tutaj odpowiedź na to z jakich obecnie narzędzi korzystam w pracy, czy też jaką mam swoją ulubioną epokę historyczną. Również Ty możesz zadać pytanie, na które udzielę odpowiedzi w wiadomości prywatnej lub na tej stronie.',
            search:{
                place:'Szukaj'
            },
            tags:[
                {
                    title:'praca',
                    value:'praca'
                },
                {
                    title:'szkoła',
                    value:'szkola'
                },
                {
                    title:'język',
                    value:'jezyk'
                },
                {
                    title:'historia',
                    value:'historia'
                },
                {
                    title:'książka',
                    value:'ksiazka'
                },
                {
                    title:'jedzenie',
                    value:'jedzenie'
                },
            ]
        },
        form:{
            firstName:{
                inputId:'firstname',
                inputName:'firstname',
                title:'Imię',
            },
            email:{
                inputId:'email',
                inputName:'email',
                title:'E-mail',
            },
            message:{
                inputId:'message',
                inputName:'message',
                title:'Pytanie',
            },
            button:{
                title:'Zapytaj'
            }
        }   
    }
}